### PR TITLE
add yarnDedupeFewer

### PR DESCRIPTION
**Pull request by itajaja**
wdyt?

### CODE REVIEW

**Comment by itajaja** [comment]
https://docs.renovatebot.com/configuration-options/#postupdateoptions

**Review by taion — APPROVED** [review]
i think the default strategy might be "highest"? idk. downgrades might be scary

**Comment by itajaja** [comment]
up to you. I think the fewer dependencies, the better. but happy to change

**Comment by taion** [comment]
merge thisss

**Comment by itajaja** [comment]
🏃 💨 👨‍💻 🏁 ✌️

**Pull request merged**
